### ISSUE TITLE
Rxjs Observable can't handle error after import module NgxProgressHttpModule

### ISSUE THREAD

**Issue by moomdate** [kKen94/ngx-progress#14]
I tried catch error different methods
`observe$.subcript(res=>{},error=>{})`
or
`observe$.pipe(catchError)`
or
```
try{
 $observa
}catch(e){

}
```
but still not working in project 

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.5.4
typescript                      4.0.7

**Comment by kKen94** [comment]
Hi, 

can you provide me a repo or a stackblitz demo? 

Thank you!

**Comment by moomdate** [comment]
[https://stackblitz.com/edit/angular-ivy-vn91zh?file=src/app/app.component.ts
](url)
Can't error after import module
